### PR TITLE
Set up TravisCI (#2)

### PR DESCRIPTION
**Pull request by lawnsea**

### CODE REVIEW

**Comment by lawnsea** [comment]
The unit tests are failing. I have a vague recollection that this was the case when we open sourced this repo. I will investigate further.

**Comment by lawnsea** [comment]
Fixed. Turns out `t.afterEach` requires async confirmation.

**Comment by lzilioli** [comment]
LGTM

**Comment by lawnsea** [comment]
Landed as ae9a58b

**Pull request closed without merging**
